# Site settings
title: ContainerCraft.io
email: admin@containercraft.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://ContainerCraft.io" # the base hostname & protocol for your site

twitter_username: ContainercraftI
github_username: containercraft

# Build settings
markdown: kramdown
