info:
  # Blog Information
  title:        "life-lessons.in"
  subtitle:     "Adventures in Software and Life"
  cover_image:  general/turkey-water.jpg
  cover_image_caption: "Istanbul, Turkey"
  about_image:  general/pottery.jpg
  about_image_caption: "Learning Pottery in Dharamshala, India"
  presentations_image:  general/pray-bells-2.jpg
  presentations_image_caption: "Prayer Bells, Dharamshala, India"
  logo:         LL-logo.png
  og-image: general/turkey-water-share.jpg
  
  # Social links
  # facebook:     sendtoinc
  twitter:      _zenx_
  github:       gsluthra
  # gplus:        '101183822199340201470'
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  "life-lessons-in"
  
  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id: 'UA-69555622-1'
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    reddit:     true
    
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

# Root URL where the site will be published
url:         http://life-lessons.in

# host 0.0.0.0 allows us to access site via sapphire.local or localhost or 127.0.0.1
host: 0.0.0.0

paginate:             20

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false